### ISSUE TITLE
In jmeter analysis phase, got warning message "Non HTTP response code"

### ISSUE THREAD

**Issue by ansonliao** [jmeter-maven-plugin/jmeter-maven-plugin-example#2]
I replaced my jmeter test plan file (*.jmx) to the example maven project.
In jmeter analysis phase, got warning message "Non HTTP response code", as below.
Could someone provide the solution to fix this problem? 

```
[INFO] --- jmeter-analysis-maven-plugin:1.0.6:analyze (default) @ demo-jmeter-stress-test ---
[INFO]  
[INFO] -------------------------------------------------------
[INFO]  A N A L Y S I N G    J M E T E R    R E S U L T S
[INFO] -------------------------------------------------------
[INFO]  
[INFO] Start index.
[INFO] End index.
[INFO] Analysing '20150716-demo.jtl'...
[WARNING] Error parsing response code 'Non HTTP response code: java.net.SocketException'
[WARNING] Error parsing response code 'Non HTTP response code: org.apache.http.conn.HttpHostConnectException'
```

**Comment by Ardesco** [comment]
It may have been due to the results being in CSV format and the analysis plugin expecting them to be in XML format.

It doesn't happen in the latest version.

**Comment by 680128** [comment]
Still looking for solution of this, facing a similar issue -  https://github.com/680128/jmeter-maven/issues/1
